language: objective-c
osx_image: xcode8.3
branches:
  only:
    - master
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/ # Execute tests for every tag with name in format "1.2.3"
    - develop
script:
  - xcodebuild test -project Clue.xcodeproj -scheme ClueTests -destination "platform=iOS Simulator,name=iPhone 7,OS=10.3" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
